mars-studio/mars/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic import TemplateView 



app_name = 'mars'

urlpatterns = [
    
    path('', views.submith_question, name="index"),#главная
    path('mars_studio/<slug:slug>/',views.DetailViewItem.as_view(), name='websait_detail'),#детальная информация
    path('about-mars-studio/',TemplateView.as_view(template_name="app/pages/about.html"), name='about'),#о нас без view
    path('etapy-raboti-mars/', TemplateView.as_view(template_name="app/pages/etapy.html"), name="etapy"),
    path('umovi-raboti-mars/', TemplateView.as_view(template_name="app/pages/umovi.html"), name="umovi"),
    path('perezapusk-saita-mars/', TemplateView.as_view(template_name="app/pages/zapusk-saita.html"), name="zapusk"),
    path('projects-all/', views.project_list, name="projects-all"),
    path('contact/', TemplateView.as_view(template_name="app/pages/contact.html"), name="contact"),
    path('poslugi-mars/', TemplateView.as_view(template_name="app/pages/poslugi.html"), name="poslugi"),
]

mars-studio/studio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mars.sitemaps import WebsaiSitemap
from django.contrib.sitemaps.views import sitemap


sitemaps = {
    'websait': WebsaiSitemap,  # Подключаем созданный Sitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),# Подключаем созданный Sitemap
    path('', include('mars.urls', namespace='mars')),#app_name
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  
    

mars-studio/mars/models.py
from django.db import models
from django.urls import reverse


class WebSait(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to='web-site/%Y/%m/%d', blank=True)
    link = models.URLField()
    created = models.DateTimeField(auto_now_add=True)  # Автоматически добавляет дату создания записи
    updated = models.DateTimeField(auto_now=True)
    
    
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created'])
        ]
        
    def __str__(self):
        return self.name 
    
    def get_absolute_url(self):
        return reverse("mars:websait_detail", kwargs={"slug": self.slug})
    
        
        
        
class Contact(models.Model):
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20)
    
    def __str__(self):
        return f"{self.name}-{self.phone_number}"

mars-studio/mars/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'phone_number']
        widgets = {
            'name': forms.TextInput(attrs={
                'class':'form-control',
                'placeholder': 'Компанія'
            }),
            'phone_number': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder' : 'Номер телефону'
                
            }),
        }

mars-studio/mars/views.py
from django.shortcuts import render, redirect
from .models import WebSait, Contact
from .forms import ContactForm
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView


def project_list(request):
    projects = WebSait.objects.all()
    return render(request,'app/pages/projects-all.html', {'projects': projects})


def submith_question(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('mars:index')
    else:
        form = ContactForm()
    
    items =   WebSait.objects.all()   
    return render(request, 'app/pages/index.html', {'form': form, 'items': items})
    

class DetailViewItem(DetailView):
    
    model = WebSait
    template_name = 'app/pages/detail.html'
    context_object_name = 'detail'
    
    
    


    
   

mars-studio/templates/app/base.html
<!doctype html>
<html lang="en">
{% load static %}
  <head> 
    <!-- Required meta tags -->
   
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- библиотека  иконок  https://cdnjs.com/libraries/font-awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">



    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
    <!-- слайдер -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>
    <!-- мой CSS -->
    <link rel="stylesheet" href="{% static 'CSS/style.css' %}">
    <!-- мой media CSS -->
    <link rel="stylesheet" href="{% static 'CSS/media.css' %}">

    <title>{% block title %}Mars studio{% endblock %}</title>
  </head>
  <body>
  <!-- секция главного экрана -->
  <section class="banner">
    <div class="image-banner"><!-- картинка  -->

      {% include 'include/menu/menu.html'%}

      <div class="banner-title-top">
        <h1>&nbsp;створення &<br>обслуговування сайтів</h1>
        <div class="mars-button"><img src="{% static 'image/кнопка.png' %}"><span>ЗАМОВИТИ</span></div>
      </div>
    </div>
  </section>
  <!-- секция главного экрана -->

   <!-- планшетная версия  главного экрана -->
  <section class="planshet-banner">
    <div class="image_planshet-banner">

      {% include 'include/menu/menu.html'%}
      
      <div class="planshet-banner-text_conteiner">
        <h1>створення &<br>обслуговування сайтів</h1>
        <div class="mars-button"><img src="{% static 'image/кнопка.png' %}"><span>ЗАМОВИТИ</span></div>
      </div>
    </div>
  </section>
  <!-- планшетная версия  главного экрана -->

   <!--   секция banner-mobile -->
  <section class="banner-mobile-section">
    <div class="banner-mobile-image">

      {% include 'include/menu/menu.html'%}
  
      <div class="banner-mobile-conteiner">
        <h1>&nbsp;&nbsp;&nbsp;створення &<br>обслуговування сайтів</h1>
        <div class="mars-button-mobile mars-button"><img src="{% static 'image/кнопка.png' %}"><span>ЗАМОВИТИ</span></div>

      </div>
    </div>
  </section><!--   секция banner-mobile -->


  {% block content %}
   

  {% endblock %}




 
  


  {% include 'include/footer/footer.html' %}

       
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
  

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


    {% block extra_scripts %}
    <!-- Дополнительные скрипты -->
    {% endblock %}

 
    <script src="/script.js"></script>
  </body>
</html>

mars-studio/templates/app/pages/projects-all.html
<!doctype html>
<html lang="en">
{% load static %}
  <head> 
    <!-- Required meta tags -->
   
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- Совместимость с Internet Explorer -->
    <meta name="description" content="Разработка интерактивных интернет-сайтов, лендингов, многостраничных интернет-магазинов и многофункциональных сайтов с адаптивным и уникальным дизайном.">
    <meta name="keywords" content="Разработка сайтов, кроссплатформенные сайты, веб-разработка, адаптивный дизайн, создание сайтов, веб-дизайн, разработка приложений, мобильные сайты">
    <meta name="author" content="Mars design studio">
    <meta name="robots" content="index, follow"> <!-- Даем инструкции для поисковых систем -->
    <meta name="google-site-verification" content="reL_Sx5gy9mocFUEHJA4ULjjJVxoGZUtpqkVioPkrTc" />

    
      <!-- Основной фавикон -->
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'image/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'image/favicon-16x16.png' %}">
    <link rel="icon" href="/path/to/favicon.ico">
  
      <!-- Apple Touch Icon для устройств Apple -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'image/apple-touch-icon.png' %}">
    
  
      <!-- Android Icon -->
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'image/android-192.png' %}">
  
      <!-- Windows Tile Icon -->
    <meta name="msapplication-TileImage" content="{% static 'image/favicon-32x32.png' %}">
  
  
  

    <!-- Open Graph для социальных сетей -->
    <meta property="og:type" content="website">
    <meta property="og:title" content="Mars design studio — Разработка интерактивных интернет-сайтов, лендингов, многостраничных интернет-магазинов и многофункциональных сайтов с адаптивным и уникальным дизайном.">
    <meta property="og:description" content="Разработка интерактивных интернет-сайтов, лендингов, многостраничных интернет-магазинов и многофункциональных сайтов с адаптивным и уникальным дизайном.">
    <meta property="og:url" content="https://www.web-mars.com/"> <!-- Здесь должен быть ваш домен -->
    <meta property="og:site_name" content="Mars design studio">
    <meta property="og:locale" content="uk_UA">
    <!-- Twitter Cards для Twitter -->
    <meta name="twitter:title" content="Mars studio — Разработка интерактивных интернет-сайтов, лендингов, многостраничных интернет-магазинов и многофункциональных сайтов с адаптивным и уникальным дизайном.">
    <meta name="twitter:description" content="Разработка интерактивных интернет-сайтов, лендингов, многостраничных интернет-магазинов и многофункциональных сайтов с адаптивным и уникальным дизайном.">
    <!-- Изображение для Twitter -->
    <!-- Иконка сайта -->
    
    <link rel="apple-touch-icon" href="https://example.com/apple-icon.png"> <!-- Для iOS устройств -->
    <!-- библиотека  иконок  https://cdnjs.com/libraries/font-awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">

    {% comment %} Inter {% endcomment %}
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">

    {% comment %} шрифт Raleway {% endcomment %}
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <script type="application/ld+json">
      {
        "@context": "https://schema.org",
        "@type": "Organization",
        "url": "https://www.web-mars.com",
        "logo": "https://www.web-mars.com/static/image/лого.png",
        "name": "Mars design studio",
        "description": "Разработка интерактивных интернет-сайтов, лендингов и интернет-магазинов.",
        "contactPoint": [
          {
            "@type": "ContactPoint",
            "telephone": "+38-099-607-2979",
            "contactType": "customer service",
            "areaServed": "UA"
          },
          {
            "@type": "ContactPoint",
            "telephone": "+38-073-160-6731",
            "contactType": "technical support",
            "areaServed": "UA"
          }
        ]
      }
    </script>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
    <!-- слайдер -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>
    <!-- мой CSS -->
    <link rel="stylesheet" href="{% static 'CSS/style.css' %}">
    <!-- мой media CSS -->
    <link rel="stylesheet" href="{% static 'CSS/media.css' %}">
    
    <title>Mars Design Studio — Разработка сайтов и веб-дизайна</title>



    <script src="{% static 'js/script.js' %}"></script>
  </head>
    <body>
        {% include 'include/menu/menu.html' %}
        <section class="bg-cover d-flex align-items-center text-center text-white" style="background-image: url('{% static "image/mars3.jpg" %}'); min-height: 700px;">
          <div class="container">
            <div class="row justify-content-center">
              <div>
                <h1 class="display-4 fw-bold">Mars<br>Cтворення сайтів c індивідуальним функціоналом</h1>
                <div class="mt-5"><a href="https://t.me/jenyatarasenko" target="_blank"><button class="btn-secondary-mars">Замовити</button></a></div>
              </div>
            </div>
          </div>
        </section>
        <section class="new-text-top-projects">
            <div class="new-text-top-conteiner" style="margin-top: 130px">
              <h5 class="new-text-block">Проєкти</h5>
            </div>
        </section>
       
        <section id="projects" class="card-context-section">
          <div class="card-context-conteiner">
          {% if projects %}  
            {% for item in projects %}
              <div class="card-context">
                <div class="card-context-img">
                  <img src="{{ item.image.url }}" class="card-image" alt="{{item.name}}" style="object-fit: cover; width: 100%; height: 200px; border-radius: 30px 30px 0 0;">
                </div>
  
                <div class="card-context-title">
                  <h5 class="vizi-text">{{ item.name|truncatechars:18  }}</h5>
                </div>
                <div class="card-context-title_items">
                <h6>{{ item.description|truncatewords:25 }}</h6>
                </div>
                <div class="card-context-title_items_button" style="top: 90px;">
                  <a href="{% url 'mars:websait_detail' item.slug %}"><div class="card-context-card mars-button-topcard" style="margin-top: 70px;">Дивитись</div></a>
                </div>
              </div>
            {% endfor %}
          {% else %} 
            <div class="new-text-center-conteiner">
              <h5 class="new-text-block">Нема проєктів</h5>
            </div>
          {% endif %}
          </div>
        </section>
        <section class="new-text-top mt-2">
            <div class="new-text-top-conteiner">
              <h5 class="new-text-block">Сайти</h5>
            </div>
          </section>
          <section class="review mt-3 py-3">
            <div class="container">
                <div class="row align-items-center justify-content-center gap-2">
                    <div class="card fixed-card bg-black" style="width: 300px; height: 300px; border-radius: 50px;">
                        <div class="card-body">
                          <!-- Изображение -->
                          <img src="{% static 'image/landing.svg' %}" class="card-img-bottom" alt="Image" style="height: 70px; width: 70px;">
                      
                          <!-- Имя -->
                          <h5 class="card-title-design mt-2 text-left text-white">Лендинг</h5>
                      
                          <!-- Текст отзыва (будет изменяться динамически) -->
                          <p class="card-text-review text-left mt-3 text-white">Це односторінковий сайт, створений для презентації товару, послуги чи пропозиції з метою заохочення користувача до конкретної дії (наприклад, купівлі, замовлення або реєстрації)</p>
                        </div>
                    </div>
                    <div class="card fixed-card bg-black" style="width: 300px; height: 300px; border-radius: 50px;">
                      <div class="card-body">
                        <!-- Изображение -->
                        <img src="{% static 'image/many.svg' %}" class="card-img-bottom" alt="Image" style="height: 70px; width: 70px;">
                    
                        <!-- Имя -->
                        <h5 class="card-title-design mt-2 text-left text-white">Багатосторінкові сайти</h5>
                    
                        <!-- Текст отзыва (будет изменяться динамически) -->
                        <p class="card-text-review text-left mt-3 text-white">Це повноцінні вебресурси, які містять декілька сторінок і підходять для компаній, що хочуть детально представити свої послуги, товари, проєкти, блог та контакти.</p>
                      </div>
                  </div>
                  <div class="card fixed-card bg-black" style="width: 300px; height: 300px; border-radius: 50px;">
                    <div class="card-body">
                      <!-- Изображение -->
                      <img src="{% static 'image/magazin.svg' %}" class="card-img-bottom" alt="Image" style="height: 70px; width: 70px;">
                  
                      <!-- Имя -->
                      <h5 class="card-title-design mt-2 text-left text-white">Інтернет магазини</h5>
                  
                      <!-- Текст отзыва (будет изменяться динамически) -->
                      <p class="card-text-review text-left mt-3 text-white">Інтернет-магазин — це сайт для онлайн-продажу товарів, з кошиком, оплатою та зручним оформленням замовлень напряму з дому.</p>
                    </div>
                </div>
                    
                </div>
            </div>
          </section>
          <section class="new-text-top mt-2">
            <div class="new-text-top-conteiner">
              <h5 class="new-text-block">питання</h5>
            </div>
          </section>
          <section class="text-question pb-3 mt-5">
            <div class="container">
              <div class="row align-items-center justify-content-center">
                <div class="col-md-3 d-flex justify-content-start flex-column">
                    <h5 class="text-vartist">Чому у нас дешевше ?</h5>
                    <div style="width: 100px; height: 3px; background-color:#E77B2D;"></div>
                </div>
                <div class="col-md-8 mt-4">
                  <h6 class="text-description-vartist">Mars Studio — це студія веброзробки, де сайт може дозволити собі всi адже у нас :висока швидкість роботи, найсучасніші технології та максимальну ефективність.</h6>
                  <h6 class="text-description-vartist">Ми працюємо на базі потужних рішень — React та Django,а наша команда щодня вкладає зусилля, щоб створювати сайти,які не просто працюють, а розвивають ваш бізнес.</h6>
                </div>
              </div>
              <div class="row align-items-center justify-content-center">
                <div class="col-md-3 d-flex justify-content-start flex-column">
                    <h5 class="text-vartist">Тривалість розробки ?</h5>
                    <div style="width: 100px; height: 3px; background-color:#E77B2D;"></div>
                </div>
                <div class="col-md-8 mt-3">
                  <h6 class="text-description-vartist">Залежно від складності проєкту: лендінг — від 5 до 10 днів, багатосторінковий сайт — від 2 тижнів. Терміни можуть змінюватися залежно від завантаженості студії, але ми завжди прагнемо виконувати проєкти швидко та якісно.</h6>

                </div>
              </div>
    
          </section>
          <div class="social-icons-fixed">
            <div class="social-circle">
                <a href="tel:+380996072979" target="_blank">
                    <img src="{% static '/image/massege.svg' %}" alt="Tel" style="width: 40px;">
                </a>
            </div>
            <div class="social-circle">
              <a href="https://t.me/jenyatarasenko" target="_blank">
                <img src="{% static '/image/massege1.svg' %}" alt="Telegram">
              </a>
            </div>
      
          </div>  
        {% include 'include/footer/footer.html' %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </body>
</html>    

mars-studio/templates/include/footer/footer.html
{% load static %}

<!-- футер destop --> 
<footer class="footer_new">
    <div class="footer_new_section">
        <div class="footer_new_conteiner_left">
            <div class="footer_new_logo">
              <img src="{% static 'image/mars-style-logo.svg' %}" alt="Mars logo" />
            </div>
            <div class="footer_new_telephone">
              <a href="tel:+380996072979">+38 (099) 607 29 79</a>
              <a href="tel:+30731606731">+38 (073) 160 67 31</a>
            </div>
            <div class="footer_new_items footer-top-deskription">
                <h6 class="vizi-text">Графік роботи:<br>пн-пт с 9.00 до 19.00/ сб, нд - вихідний.</h6>
            </div>
            <div class="footer-icon-mobile footer_new_mobile">
                <a href="https://www.facebook.com/profile.php?id=61560573721784"><img src="{% static '/image/facebook-icons.png' %}" alt="" class="image-conteiner-items"></a>
                <img src="{% static '/image/behance.png' %}" alt="" class="image-conteiner-items">
                <a href="https://www.instagram.com/mars_webstudio/"><img src="{% static '/image/instagramm.png' %}" alt="" class="image-conteiner-items"></a>
                <img src="{% static '/image/pinterest.png' %}" alt="" class="image-conteiner-items">
            </div>
            <div class="footer_new_item_text">
                всі права захищені - Web Studio “Mars” 2024 
            </div>

        </div>
        <div class="footer_new_conteiner_right">
            <div class="footer_new_item-one">
                <h6 class="vizi-text text-footer">документ</h6>
                <div class="footer_new_item-one-downloud">
                    <a href="путь_к_вашему_файлу" download>Умови роботи</a>
                    <a href="путь_к_вашему_файлу" download>Етапи роботи</a>
                    <a href="путь_к_вашему_файлу" download>Договір</a>
                    <a href="путь_к_вашему_файлу" download>Призентація студії</a>
                </div>
                
                <div class="footer_new_item-one_item">
                    <h6 class="vizi-text text-footer">сервіс</h6>
                    <div class="footer_new_item-one-downloud">
                        <a href="путь_к_вашему_файлу" download>Адміністрування сайту</a>
                        <a href="путь_к_вашему_файлу" download>Призентація студії</a>
                    </div>
                </div>
            </div>
            <div class="footer_new_item_two">
                <h6 class="vizi-text text-footer">Меню</h6>
                <a href="{% url "mars:index" %}" class="footer-top-style">Головна</a>
                <a href="/#projects" class="footer-top-style">Проекти
                <a href="/#poslugi" class="footer-top-style">Послуги</a>
            </div>
        </div>
    </div>
</footer> <!-- футер destop --> 




<!-- футер mobile --> 
<footer class="mobile-footer_section">
  <div class="mobile-footer_image">
    <div class="mobile-footer-section_conteiner">
      <div class="mobile-footer-telephone">
        <a href="tel:+380996072979" class="phone-button">+38 (099) 607 29 79</a>
        <a href="tel:+30731606731" class="phone-button">+38  (073) 160 67 31</a>
      </div>
      <div class="mobile-footer-description">
        <p>Графік роботи:</p>
        <h6 class="vizi-text">пн-пт с 9.00 до 19.00/ сб, нд - вихідний.</h6>
      </div>
      <div class="mobile-conteiner-image_icon">
        <a href="https://www.facebook.com/profile.php?id=61560573721784"><img src="{% static '/image/facebook-icons.png' %}" class="image-conteiner-items"></a>
        <a href=""><img src="{% static '/image/behance.png' %}" class="image-conteiner-items"></a>
        <a href="https://www.instagram.com/mars_webstudio/"><img src="{% static '/image/instagramm.png' %}" class="image-conteiner-items"></a>
        <a href=""><img src="{% static '/image/pinterest.png' %}"class="image-conteiner-items"></a>
      </div>
      <div class="mobile-conteiner_prava">
        <p>всі права захищені - Web Studio “Mars” 2024 </p>
      </div>


    </div>

  </div>
</footer><!-- футер mobile --> 

mars-studio/templates/include/form/contact_form.html
{% load static %}

 
<section id="form-top" class="form-in-line-top">
    <div class="form-img-conteiner">
      <div class="form-conteiner-top">

        <div class="form-conteiner-top-text">
          <h6 class="form-top-form">ВІДПРАВЬТЕ ЗАЯВКУ!</h6>
        </div>
        
          <form class="form-inline-top" method="post" action="">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" name="{{ form.name.name }}" class="form-control" placeholder="Kомпанія" value="{{ form.name.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <input type="text" name="{{ form.phone_number.name }}" class="form-control" placeholder="Номер телефону" value="{{ form.phone_number.value|default_if_none:'' }}">
            </div>
            <button type="submit" class="form-button">
              Замовити
            </button>
          </form>
        
      </div>
    </div>

</section> 

mars-studio/templates/include/menu/menu.html
{% load static %}
<!-- навигация  -->




<body class="{% if 'umovi-raboti-mars' in request.path %}page-umovi{% elif 'about-mars-studio' in request.path %}page-about{% elif 'etapy-raboti-mars' in request.path %}page-raboti{% endif %}">

  <nav class="navbar navbar-expand-lg" style="position: absolute; top: 0; left: 0; right: 0; z-index: 100; background-color: #000000;">
    <div class="container d-flex align-items-center">
      {% comment %} контейнер лля 1280px {% endcomment %}
     
         <!-- Логотип -->
        <a class="navbar-brand" href="#">
          <img src="{% static 'image/mars-style-logo.svg' %}" alt="Mars logo"  class="d-block">
        </a>
        <!-- Бургер-меню -->
        <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <div class="burger-icon">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
          </div>
        </button>
        <!-- Навигация -->
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item">
              <a class="nav-link  py-4 {% if request.path == '/' %}active{% endif %}" aria-current="page" href="{% url 'mars:index' %}">Головна</a>
            </li>
            <li class="nav-item">
              <a class="nav-link  py-4 {% if request.path == '/about-mars-studio/' %}active{% endif %}" href="{% url 'mars:about' %}">Про нас</a>
            </li>
            <li class="nav-item">
              <a class="nav-link  py-4 {% if request.path == '/poslugi-mars/' %}active{% endif %}" href="{% url 'mars:poslugi' %}">Послуги</a>
            </li>
            <li class="nav-item">
              <a class="nav-link  py-4 {% if request.path == '/projects-all/' %}active{% endif %}" href="{% url 'mars:projects-all' %}">Проєкти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link  py-4 {% if 'umovi-raboti-mars' in request.path  %}active{% endif %}"href="{% url 'mars:umovi' %}">Умови</a>
            </li>
            <li class="nav-item">
              <a class="nav-link  py-4 {% if 'etapy-raboti-mars/' in request.path  %}active{% endif %}" href="{% url 'mars:etapy' %}">Етапи</a>
            </li> 
            <li class="nav-item">
              <a class="nav-link  py-4 {% if 'contact/' in request.path  %}active{% endif %}" href="{% url 'mars:contact' %}" >Контакти</a>
            </li>
          </ul>
        </div>
      
      
      {% comment %} контейнер лля 1280px {% endcomment %} 
    </div>
  </nav> 
  
</body>



<!-- навигация  -->